In [1]:
import numpy as np
from scipy.spatial.distance import cdist

# Danh sách vector A
A = np.array([
    [2.0, 3.0, 4.0],
    [5.0, 6.0, 7.0],
    [8.0, 9.0, 10.0]
])

# Các mean của các lớp
means = np.array([
    [1.0, 2.0, 3.0],  # mean class 0
    [4.0, 5.0, 6.0],  # mean class 1
    [7.0, 8.0, 9.0],  # mean class 2
    [10.0, 11.0, 12.0]  # mean class 3
])

# Tính ma trận khoảng cách (vd: Euclidean)
distance_matrix = cdist(A, means, metric='euclidean')

# Hiển thị kết quả
print("Ma trận khoảng cách giữa A và means:")
print(distance_matrix)


Ma trận khoảng cách giữa A và means:
[[ 1.73205081  3.46410162  8.66025404 13.85640646]
 [ 6.92820323  1.73205081  3.46410162  8.66025404]
 [12.12435565  6.92820323  1.73205081  3.46410162]]


In [2]:
import torch

ModuleNotFoundError: No module named 'torch'